---
title: <h1 style="color:black;font-size:40px;font-family:georgia"> Dear Me </h1>
--- 

<html>
<body style="background-color:seashell;">

<p style="font-family:georgia">  
Dear 16 year old me, </br> 

I’m sure you don’t believe it’s me. So here are a few things to help prove it. You didn’t wreck your car that icy night, but you took the fall so your best friend didn’t get in trouble. You kept your tip money in your old m&m jar, hoping to save up enough money to buy a plane ticket to fly far away from the cornfields and back roads. And your biggest kept secret was county road 40 was the one place you would go over 100 on, listening to whatever heartbreak song, to try to fill the void in your heart. <br> 

Do you believe it’s me now? Good. Because I have some stuff to say. </br> 

First off, quit wearing so much eye make-up. It’s not cute and it’s just taking away from the natural beauty of the blue eyes your mother gave you. Stop worrying so much about what every other girl in your high school thinks of you. Because in a couple of years the girl you sit next to in class every day, the girl you defend day in and day out and say is your “best friend,” picks a boy over you and really never speaks to you again. Stick to your goals and don’t be afraid to try new things, because you know that out of everyone in your graduating class you’re going to be one of the few that leaves the small town and finds something bigger than working in a factory or a nursing home. </br> 

Quit letting that boy control everything in your life. He might say he “loves you” but his actions are not “love”. He does not want to marry you. He can’t even remember your birthday or your favorite color. Stop bending over backward for him, and stop letting him walk all over you. He is going to move on the minute you walk away like it is nothing and yes it’s going to hurt. You’re going to learn so much from him, and you’re going to go through what feels like the biggest heartbreak of all time. It’s going to feel like you will never be able to move on or find love again. But I promise you, that you will.  You’re going to find a man in several years who remembers your Starbucks order, and reminds you daily that you’re beautiful, even when you feel like you aren’t. </br> 

The friends you want to keep forever, they are going to disappear. And yes it hurts. You realize that there is a difference between real friends because they love you and value your friendship and because it is a convenient thing. Do not get hung up on losing those fake friends, and do not hang onto the friendships that have run their course, because it is exhausting, and it just leaves you hurting more. Hold the ones who are there for you close, because those girls, will be next to you through some of the toughest battles you will face. <br> 

Call your grandparents. Daily. Weekly. Try to visit more. Do things with them. Because the time you think you have. You don’t. Life is too short and you get so caught up in the moment and in yourself, you forget that they are getting older and their time with you is slowly coming to an end. You’re going to lose both of your grandpa’s unexpectedly and you’re going to be crushed. Don’t forget about them. <br> 

And most importantly, put yourself first for once. You are always worried about others, and you never remember that you have to worry about you as well. Your dreams and your wants are important and you have to put your happiness before anyone else because once you fall in love with you and find your happiness then life will fall into place. </br> 

Love 21 year old me <br> 

P.S. It’s okay to go to Starbucks. 



</body>
</html>