---
title: <p style="color:purple;font-size:40px"><b>Hello 20's </p>
---
20 trips around the sun.That's how long I've been on this beautiful planet. 20 years, and it is crazy to me to look back on all the things I've seen, all the things I've felt, all the things I've done. I am sure everyone has this moment in their life, where they reflect on their time here. I suppose I just never had that moment, until now. 

I am no long a teenager, even though I have the attitude of a carefree teen. I know that my days of being reckless and wild are slowly drifting away. It blows my mind that throughout this next decade, I'll graduate college, join the real working world. My friends will be getting married, or starting their families and hopefully I will be too. My younger siblings will be going through their teen years, while my older sibling is walking through his twenties right with me. 

The first decade I don't remember as much, since most of it was spent crying, learning to talk, walk, read, the normal life functions of a human being. From what I do remember was a lot of heartbreak, but not like the boy heart break. The heartbreak of being a child of divorced parents, from missing my dad a lot. I remember getting my first crush, his name was Micheal, we were elementary sweethearts you could say. I remember when we held hands during reading time in third grade, my heart was racing, and I thought we would get in so much trouble. I remember my brother convincing me to put my bike on the back of a wagon, then going down a hill. It ended poorly. I remember my mom finding her father after almost 28 years. I gained a grandpa that day, a whole bunch of uncles, and I had no idea how much they would affect me. I remember my uncle George making hot dogs for dinner everyday for a year! I still can't eat them. I remember meeting Steven and Codey, back then they were just some annoying boys, but now I can't even imagine life without them or their families. I remember I went to an indoor water park for my 10th birthday, that was when my grandma could still drive, and my mom worked day in and day out to support her family so she couldn't come. 

The second decade though, that's when it started to get a little wild. I had my first kiss, I told my parents I was going to my friends house but I was really going to the park. I made my first girl best friend, we planned our lives together, she was going to move to Tennessee and I was going to live in North Carolina. We were going to have helicopters to travel faster to each other. Now we don't even speak. I became the girl obsessed with football, the passion only grows deeper every day. I went through changes, mentally, physically and emotionally, losing over 50 pounds, no longer crying in the changing rooms at stores. I failed tests, and I excelled in things outside the classroom, like how to be a good older sister, or a better listener. I made new friends, girls who are now sisters, who will probably be by my side when I finally say "I do". I laughed a lot, at myself and my friends. Had my breathe taken away by the beauty of the world, and a simple four word sentence "I love you too". Experienced loss of four men who helped raise me, all terrible deaths, all too soon. Fell in and out of love with a boy I would have done anything and everything for. Spent many late nights wondering if I would be enough for anyone. Told white lies to my parents. Had dreams that I knew I needed to pursue. The normal teenage experience. 

As stated before I've done a lot of things these past two decades. Been a lot of places, met a lot of people, spent a lot of money, ate a lot of food. Two decades and I've seen a baby be born, while I've seen a life take their last breath. I've seen a mother hug her solider after being away from home for 9 months. I've seen a girl conquer her fears. I've seen hard work and dedication pay off. I've seen a girl say yes to spending the rest of her life with her best friend, then turn around to ask me be part of her big day. I watched my mom battle breast cancer, beating it like Tom Brady and his Super Bowl wins. I gained a whole new family, from my best friends, coaches and teammates. I've seen my first love fall in love with someone else, then come back to me just to break me again. I've seen a mother burying her 16 year old child. I've seen someone end their life because things were just too hard. I've seen a girl destroy herself for a boy who never had the intentions to love her. I've seen a boy standing at the edge with a gun to his head because he lost hope. I've seen a mother lose her unborn child. I've seen an alcoholic finally admitting he had a problem. I've seen a marriage of 20 years come to an end due to lack of faith and compassion. I've seen cancer take away the backbone of a family. I've seen a face full of black smeared make-up, red puffy eyes glossed over with tears staring back me in the mirror trying to figure out when the pain would end. In just 19 years, I've seen endless amount of love, honesty, heartbreak, laughter, and so much more. 

I truly believe that everything a person experiences in these two decades, not only helps mold them. But shows them who they are, giving them a hint of life, a taste of the future. The girl I was these past two decades will change, mold into a new person, but the past, the memories they will always be in the back of my mind. A reminder of where I came from, what my morals are, and even when I think I can't get through whatever battle I am facing, I'll remember everything I've been through, and remember I can find the strength inside me to get through it again. 

Here is to a new decade, and a new chapter in these beautiful trips around the sun.  