---
title: <h1 style="color:black;font-size:40px;font-family:georgia"> Real love, not Truelove </h1>
--- 

<html>
<body style="background-color:seashell;">

<p style="font-family:georgia">  

As a little girl love was something I pictured as a princess getting saved by her prince. The fairytale style love that pretty much every little girl would watch on their box tv while wearing their princess pajamas. I mean even the age of 21 I still enjoy my Disney princess movies. <br>

But as I got older I found out love wasn’t just the happy endings. It’s about all the hard work and sacrifice to get to that point. <br>

It’s not easy to find a person who is willing to commit to you, and just be about you these days. with the ability to talk to whoever, whenever and wherever it seems like people fear commitment more than anything in this world. it's not easy to find someone who chooses you, which means being faithful when things get hard - when there’s uncertainty, doubt. <br> 

And when it comes to love, it's not because you need them but because you **want** them. your heart chooses them. <br> 

Anyways, I know love isn't easy, because I've invested a love of love into a handful of wrong people. I've cried enough tears to make me believe that I will never love again. Until I met him. <br> 

Meeting him wasn’t exactly love at first sight. I actually couldn’t stand him. We would bicker daily and we definitely knew how to get under each other’s skin. <br> 

But as time went on, we grew into friends. I mean it was our only choice since we saw each other daily. We had each other in classes, and started to make inside jokes. We weren’t complete jerks to each other. <br> 

Over two years and our relationship was completely platonic friendship. Then one day it completely changed, out of the blue. He was no longer the boy that i sat next to in class that drew on my notes, or made fun of me for whatever I posted on facebook the night before. He was someone that I could actually see myself with. <br> 

We tried to take things to the next step, and we both wanted very different things at first, and it was hard. I am the hopeless romantic that tries way too hard for someones love, and he was the hardshell boy, who never showed an ounce of emotions unless its  during video games. <br> 

Things ended, and it hurt. I would be lying if I said I didn’t cry for a few nights after everything happened. We both did our own thing for a few months, and I spent a majority of those months praying he would find his way back to me. I gave myself a time frame, and I told myself *if he didn’t return the feelings by this date then I have to move on* <br> 

And after waiting for what felt like eternity, and watching him from the distance do his thing with other girls, one day something changed, and he came back. I couldn’t hide my excitement when I called my best friend. Because I knew he was the one I was waiting for. <br> 
Months later, we are official, and I couldn’t be more excited. Because he has been everything I have been waiting for and then some. I was patience enough to not settle for someone that didn’t give me what I deserved. I waited and prayed and I found him. <br> 

No we don’t have the fairytale relationship, but he does drive 45 minutes for me to get ice cream, or turns the heater on for me when he gets up early so I am not freezing when I finally wake up. He doesn’t buy me flowers or write me love letters, but he has my starbucks order under his visor and he gets me Panera even though he can’t stand it there. He isn’t the prince charming to most girls but to me he is the man I have been waiting for my whole life. And that is what makes our love story my **favorite**. <br> 


</body>
</html>
