---
title: <h1 style="color:black;font-size:40px;font-family:georgia"> Wrong kind of Love </h1>
--- 

<html>
<body style="background-color:seashell;">

<p style="font-family:georgia"> 

i thought i found love when i was 16. i mean i really thought i was going to marry this boy. he was in my mind the *prince charming* i had been looking for. sixteen and blinded by love, innocent, clueless love. as if some 16 year old really knows what love is, and if i am being honest, i love a little too hard. <br> 

he was the boy i wanted to have forever, the one i held on a little too long. we had so many wonderful moments and he told me that i was his *forever*. there was the endless laughter and the long night drives that made me think that he really meant we would be together till the end of time. <br> 

so at for two years, i spend days and nights doing anything and everything for a boy who really had no intentions to return the favor. he really tore me down, but at the same time i allowed him too. and every chance i had to leave i found a reason to stay. <br>

it really left me **exhuasted** i had no motivation to do anything i used to love doing. i was no longer the girl who looked up at the stars in amazement. no longer sang my heart out to every love song playing on the radio. no longer laughed at everything, or smiled daily. he destroyed me, convinced me i was worthless and brought out demons inside of me darker than the night sky. i was truly broken. <br> 

he took advantage of my heart, of my kindness, and my compassion. i poured myself into him, letting my love for him consume me to a point where i didn't even know who i was, becoming who he wanted me to be. i lost sight of myself, and of what i wanted in life. all because i **loved** him. <br> 

but he didn't just break my heart, he broke my soul. he took the girl who was strong, compassionate, and who laughed at everything and pushed her to the point where she felt so much, but at the same time felt nothing at all. no matter how hard i  tried, i always fell short. even though i cried myself to sleep day in and day out. i still loved him with every bit of my heart. i still cared for him and put him above everyone <br>

even though hr turned out to be the villain in this love story, i pray for you. every day. i constantly pray that God gives him guidance, faith, and the ability to love someone as much as they love him. i pray that whatever darkness inside him fades, and he see all the wrong he has  done. i pray he never put another girl through this. But i don't miss him, the lies, negative words, or the endless pain. i don't want him back. i don't want to go back to that place in my life because i'm still not over it. it's going to take a long time for me to heal from all the pain i went through. i am slowly finding my own happiness in life, and the meaning of truly loving myself for once. <br>

i want to forgive him, i really do, but not today. right now my heart is hurting and the pain in my chest still aches. i need time to just grieve and figure this all out. but one day i'll forgive you. it might be a day, a week, month or year but i'll forgive him. he will always be a reminder of what i don’t deserve. right now, it’s time for me to close this chapter in my life. but don’t worry because i’ll pray for him.<br> 

*this is a letter i wrote for an assignment durning my junior year of college. it was to address the first boy i had ever loved and dated. if you are or know anyone who is an abuseive relationship (physical, mentally, or emotionally) there is help out there 1-800-799-SAFE (7233)*  







</body>
</html>
