---
title: <h1 style="color:black;font-size:40px;font-family:georgia">Perfectly Imperfect </h1>
---

<html>
<body style="background-color:seashell;">

<p style="font-family:georgia"> i'm a teenage girl in today's society <br>
i feel the pressure everyday to look like the girls people idolize on tv <br>
i feel the pressure to be something i'm not <br>
i'm a teenage girl in today's society <br>
who isn't a size 0 <br>
who doesn't have a perfect smile <br>
who doesn't get a thousand likes on a photo <br>
i'm a teenage girl in today's society <br>
who doesn't have a clue what she wants in life <br>
who doesn't have an idea of what path to take <br>
who feels like she's drowning most of the time <br>
i'm a teenage girl in today's society <br>
who feels the standard she has to reach are higher than she can jump <br>
who feels like no matter how hard she tries it isn't enough <br>
who is constantly worried about failing, she's too afraid to try <br>
i'm a teenage girl in today's society <br>
i'm overwhelmed with the idea of being perfect <br> 
who is afraid to speak her mind in the fear of being wrong <br>
who needs more confidence and less doubt <br>
i am a teenage girl in today's society <br> 
who doesn't need a man to be happy <br>
who doesn't think money is everything <br> 
who doesn't need the expensive wardrobe <br> 
i am a teenage girl in today's society <br> 
who enjoys getting lost in a book <br> 
who eats the the piece of cake <br> 
who likes her sweats and a lazy day <br> 
i might not be everything many of us teenage girls feel the anxiety to be <br> 
but i'm not going to let it define me </p>


</body>
</html>


